[project]
name = "samfundet-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepface>=0.0.96",
    "gradio>=5.50.0",
    "insightface>=0.7.3",
    "onnxruntime>=1.23.2",
    "python-dotenv>=1.2.1",
    "qdrant-client>=1.16.1",
    "supabase>=2.24.0",
    "tf-keras>=2.20.1",
]
